version: 0.1

phases:

  install:
    commands:
      - npm install --prefix src/web/start
      - npm install --prefix src/dbpopulate

  build:
    commands:
     - ./build/build.sh

  post_build:
    commands:
     - ./build/publish.sh
