AWSTemplateFormatVersion: 2010-09-09

Description: Resources used in the caching part of the scaling lab

Parameters:

  CacheVPC:
    Type: AWS::EC2::VPC::Id
    Description: Which VPC will the cache run in?

  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Which subnets should the cache be deployed to?

Resources:

  CacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnets used by the web app scaling lab cache
      SubnetIds: !Ref Subnets

  CacheSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties: 
      GroupDescription: Rules applied to cache instances
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      VpcId: !Ref CacheVPC

  CacheCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: cache.t2.micro
      CacheSubnetGroupName: !Ref CacheSubnetGroup
      Engine: redis
      NumCacheNodes: 1
      VpcSecurityGroupIds:
        - !Ref CacheSecurityGroup
